# Generated by Django 3.2 on 2021-11-05 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
